function outList = getConditionNames(condition)
%GETCONDITIONLIST Summary of this function goes here
%   Detailed explanation goes here

switch condition
    case 'all_betas'
        outList = {'fr_ba_rep1', 'fr_ba_rep2', 'fr_ba_rep3', 'fr_ba_rep4',...
            'fr_va_rep1', 'fr_va_rep2', 'fr_va_rep3', 'fr_va_rep4',...
            'fr_co_rep1', 'fr_co_rep2', 'fr_co_rep3', 'fr_co_rep4',...
            'fr_fa_rep1', 'fr_fa_rep2', 'fr_fa_rep3', 'fr_fa_rep4',...
            'fr_ch_rep1', 'fr_ch_rep2', 'fr_ch_rep3', 'fr_ch_rep4',...
            'fr_so_rep1', 'fr_so_rep2', 'fr_so_rep3', 'fr_so_rep4',...
            'fr_po_rep1', 'fr_po_rep2', 'fr_po_rep3', 'fr_po_rep4',...
            'fr_ro_rep1', 'fr_ro_rep2', 'fr_ro_rep3', 'fr_ro_rep4',...
            'br_ba_rep1', 'br_ba_rep2', 'br_ba_rep3', 'br_ba_rep4',...
            'br_va_rep1', 'br_va_rep2', 'br_va_rep3', 'br_va_rep4',...
            'br_co_rep1', 'br_co_rep2', 'br_co_rep3', 'br_co_rep4',...
            'br_fa_rep1', 'br_fa_rep2', 'br_fa_rep3', 'br_fa_rep4',...
            'br_ch_rep1', 'br_ch_rep2', 'br_ch_rep3', 'br_ch_rep4',...
            'br_so_rep1', 'br_so_rep2', 'br_so_rep3', 'br_so_rep4',...
            'br_po_rep1', 'br_po_rep2', 'br_po_rep3', 'br_po_rep4',...
            'br_ro_rep1', 'br_ro_rep2', 'br_ro_rep3', 'br_ro_rep4'};

    otherwise 
        outList = {'fr_ba', 'fr_va', 'fr_co', 'fr_fa', ...
                   'fr_ch', 'fr_so', 'fr_po', 'fr_ro', ...
                   'br_ba', 'br_va', 'br_co', 'br_fa', ...
                   'br_ch', 'br_so', 'br_po', 'br_ro'};
        
  % outList = {'fr_ba', 'fr_va', 'fr_co', 'fr_fa', ...
%            'fr_ch', 'fr_so', 'fr_po', 'fr_ro', ...
%            'br_ba', 'br_va', 'br_co', 'br_fa', ...
%            'br_ch', 'br_so', 'br_po', 'br_ro'};
%        
       
end

