function outList = getConditionList()
%GETCONDITIONLIST Summary of this function goes here
%   Detailed explanation goes here

outList = {... FR balcon
           'fr_balcon_v_fr_vallon', 'fr_balcon_v_fr_cochon', 'fr_balcon_v_fr_faucon', ...
           'fr_balcon_v_fr_chalet', 'fr_balcon_v_fr_sommet', 'fr_balcon_v_fr_poulet', 'fr_balcon_v_fr_roquet', ...
           'fr_balcon_v_br_balcon', 'fr_balcon_v_br_vallon', 'fr_balcon_v_br_cochon', 'fr_balcon_v_br_faucon', ...
           'fr_balcon_v_br_chalet', 'fr_balcon_v_br_sommet', 'fr_balcon_v_br_poulet', 'fr_balcon_v_br_roquet', ...
           ... vallon 
           'fr_vallon_v_fr_balcon', 'fr_vallon_v_fr_cochon', 'fr_vallon_v_fr_faucon', ...
           'fr_vallon_v_fr_chalet', 'fr_vallon_v_fr_sommet', 'fr_vallon_v_fr_poulet', 'fr_vallon_v_fr_roquet', ...
           'fr_vallon_v_br_balcon', 'fr_vallon_v_br_vallon', 'fr_vallon_v_br_cochon', 'fr_vallon_v_br_faucon', ...
           'fr_vallon_v_br_chalet', 'fr_vallon_v_br_sommet', 'fr_vallon_v_br_poulet', 'fr_vallon_v_br_roquet', ...
           ... cochon 
           'fr_cochon_v_fr_balcon', 'fr_cochon_v_fr_vallon', 'fr_cochon_v_fr_faucon', ...
           'fr_cochon_v_fr_chalet', 'fr_cochon_v_fr_sommet', 'fr_cochon_v_fr_poulet', 'fr_cochon_v_fr_roquet', ...
           'fr_cochon_v_br_balcon', 'fr_cochon_v_br_vallon', 'fr_cochon_v_br_cochon', 'fr_cochon_v_br_faucon', ...
           'fr_cochon_v_br_chalet', 'fr_cochon_v_br_sommet', 'fr_cochon_v_br_poulet', 'fr_cochon_v_br_roquet', ...
           ... faucon 
           'fr_faucon_v_fr_balcon', 'fr_faucon_v_fr_vallon', 'fr_faucon_v_fr_cochon', ...
           'fr_faucon_v_fr_chalet', 'fr_faucon_v_fr_sommet', 'fr_faucon_v_fr_poulet', 'fr_faucon_v_fr_roquet', ...
           'fr_faucon_v_br_balcon', 'fr_faucon_v_br_vallon', 'fr_faucon_v_br_cochon', 'fr_faucon_v_br_faucon', ...
           'fr_faucon_v_br_chalet', 'fr_faucon_v_br_sommet', 'fr_faucon_v_br_poulet', 'fr_faucon_v_br_roquet', ...
           ... chalet 
           'fr_chalet_v_fr_balcon', 'fr_chalet_v_fr_vallon', 'fr_chalet_v_fr_cochon', 'fr_chalet_v_fr_faucon', ...
           'fr_chalet_v_fr_sommet', 'fr_chalet_v_fr_poulet', 'fr_chalet_v_fr_roquet', ...
           'fr_chalet_v_br_balcon', 'fr_chalet_v_br_vallon', 'fr_chalet_v_br_cochon', 'fr_chalet_v_br_faucon', ...
           'fr_chalet_v_br_chalet', 'fr_chalet_v_br_sommet', 'fr_chalet_v_br_poulet', 'fr_chalet_v_br_roquet', ...
           ... sommet 
           'fr_sommet_v_fr_balcon', 'fr_sommet_v_fr_vallon', 'fr_sommet_v_fr_cochon', 'fr_sommet_v_fr_faucon', ...
           'fr_sommet_v_fr_chalet', 'fr_sommet_v_fr_poulet', 'fr_sommet_v_fr_roquet', ...
           'fr_sommet_v_br_balcon', 'fr_sommet_v_br_vallon', 'fr_sommet_v_br_cochon', 'fr_sommet_v_br_faucon', ...
           'fr_sommet_v_br_chalet', 'fr_sommet_v_br_sommet', 'fr_sommet_v_br_poulet', 'fr_sommet_v_br_roquet', ...
           ... poulet 
           'fr_poulet_v_fr_balcon', 'fr_poulet_v_fr_vallon', 'fr_poulet_v_fr_cochon', 'fr_poulet_v_fr_faucon', ...
           'fr_poulet_v_fr_chalet', 'fr_poulet_v_fr_sommet', 'fr_poulet_v_fr_roquet', ...
           'fr_poulet_v_br_balcon', 'fr_poulet_v_br_vallon', 'fr_poulet_v_br_cochon', 'fr_poulet_v_br_faucon', ...
           'fr_poulet_v_br_chalet', 'fr_poulet_v_br_sommet', 'fr_poulet_v_br_poulet', 'fr_poulet_v_br_roquet', ...
           ... roquet 
           'fr_roquet_v_fr_balcon', 'fr_roquet_v_fr_vallon', 'fr_roquet_v_fr_cochon', 'fr_roquet_v_fr_faucon', ...
           'fr_roquet_v_fr_chalet', 'fr_roquet_v_fr_sommet', 'fr_roquet_v_fr_poulet', ...
           'fr_roquet_v_br_balcon', 'fr_roquet_v_br_vallon', 'fr_roquet_v_br_cochon', 'fr_roquet_v_br_faucon', ...
           'fr_roquet_v_br_chalet', 'fr_roquet_v_br_sommet', 'fr_roquet_v_br_poulet', 'fr_roquet_v_br_roquet', ...
           ... BR balcon
           'br_balcon_v_fr_balcon', 'br_balcon_v_fr_vallon', 'br_balcon_v_fr_cochon', 'br_balcon_v_fr_faucon', ...
           'br_balcon_v_fr_chalet', 'br_balcon_v_fr_sommet', 'br_balcon_v_fr_poulet', 'br_balcon_v_fr_roquet', ...
           'br_balcon_v_br_vallon', 'br_balcon_v_br_cochon', 'br_balcon_v_br_faucon', ...
           'br_balcon_v_br_chalet', 'br_balcon_v_br_sommet', 'br_balcon_v_br_poulet', 'br_balcon_v_br_roquet', ...
           ... vallon 
           'br_vallon_v_fr_balcon', 'br_vallon_v_fr_vallon', 'br_vallon_v_fr_cochon', 'br_vallon_v_fr_faucon', ...
           'br_vallon_v_fr_chalet', 'br_vallon_v_fr_sommet', 'br_vallon_v_fr_poulet', 'br_vallon_v_fr_roquet', ...
           'br_vallon_v_br_balcon', 'br_vallon_v_br_cochon', 'br_vallon_v_br_faucon', ...
           'br_vallon_v_br_chalet', 'br_vallon_v_br_sommet', 'br_vallon_v_br_poulet', 'br_vallon_v_br_roquet', ...
           ... cochon 
           'br_cochon_v_fr_balcon', 'br_cochon_v_fr_vallon', 'br_cochon_v_fr_cochon', 'br_cochon_v_fr_faucon', ...
           'br_cochon_v_fr_chalet', 'br_cochon_v_fr_sommet', 'br_cochon_v_fr_poulet', 'br_cochon_v_fr_roquet', ...
           'br_cochon_v_br_balcon', 'br_cochon_v_br_vallon', 'br_cochon_v_br_faucon', ...
           'br_cochon_v_br_chalet', 'br_cochon_v_br_sommet', 'br_cochon_v_br_poulet', 'br_cochon_v_br_roquet', ...
           ... faucon 
           'br_faucon_v_fr_balcon', 'br_faucon_v_fr_vallon', 'br_faucon_v_fr_cochon', 'br_faucon_v_fr_faucon', ...
           'br_faucon_v_fr_chalet', 'br_faucon_v_fr_sommet', 'br_faucon_v_fr_poulet', 'br_faucon_v_fr_roquet', ...
           'br_faucon_v_br_balcon', 'br_faucon_v_br_vallon', 'br_faucon_v_br_cochon', ...
           'br_faucon_v_br_chalet', 'br_faucon_v_br_sommet', 'br_faucon_v_br_poulet', 'br_faucon_v_br_roquet', ...
           ... chalet 
           'br_chalet_v_fr_balcon', 'br_chalet_v_fr_vallon', 'br_chalet_v_fr_cochon', 'br_chalet_v_fr_faucon', ...
           'br_chalet_v_fr_chalet', 'br_chalet_v_fr_sommet', 'br_chalet_v_fr_poulet', 'br_chalet_v_fr_roquet', ...
           'br_chalet_v_br_balcon', 'br_chalet_v_br_vallon', 'br_chalet_v_br_cochon', 'br_chalet_v_br_faucon', ...
           'br_chalet_v_br_sommet', 'br_chalet_v_br_poulet', 'br_chalet_v_br_roquet', ...
           ... sommet 
           'br_sommet_v_fr_balcon', 'br_sommet_v_fr_vallon', 'br_sommet_v_fr_cochon', 'br_sommet_v_fr_faucon', ...
           'br_sommet_v_fr_chalet', 'br_sommet_v_fr_sommet', 'br_sommet_v_fr_poulet', 'br_sommet_v_fr_roquet', ...
           'br_sommet_v_br_balcon', 'br_sommet_v_br_vallon', 'br_sommet_v_br_cochon', 'br_sommet_v_br_faucon', ...
           'br_sommet_v_br_chalet', 'br_sommet_v_br_poulet', 'br_sommet_v_br_roquet', ...
           ... poulet 
           'br_poulet_v_fr_balcon', 'br_poulet_v_fr_vallon', 'br_poulet_v_fr_cochon', 'br_poulet_v_fr_faucon', ...
           'br_poulet_v_fr_chalet', 'br_poulet_v_fr_sommet', 'br_poulet_v_fr_poulet', 'br_poulet_v_fr_roquet', ...
           'br_poulet_v_br_balcon', 'br_poulet_v_br_vallon', 'br_poulet_v_br_cochon', 'br_poulet_v_br_faucon', ...
           'br_poulet_v_br_chalet', 'br_poulet_v_br_sommet', 'br_poulet_v_br_roquet', ...
           ... roquet 
           'br_roquet_v_fr_balcon', 'br_roquet_v_fr_vallon', 'br_roquet_v_fr_cochon', 'br_roquet_v_fr_faucon', ...
           'br_roquet_v_fr_chalet', 'br_roquet_v_fr_sommet', 'br_roquet_v_fr_poulet', 'br_roquet_v_fr_roquet', ...
           'br_roquet_v_br_balcon', 'br_roquet_v_br_vallon', 'br_roquet_v_br_cochon', 'br_roquet_v_br_faucon', ...
           'br_roquet_v_br_chalet', 'br_roquet_v_br_sommet', 'br_roquet_v_br_poulet', ...
           };


end

